services:
    back:
        image: t84ar7xr.kr.private-ncr.ntruss.com/back:dev
        container_name: back
        environment:
            DATABASE_URL: ${DATABASE_URL}
        ports:
            - '3000:3000'
        entrypoint: sh -c "npx prisma generate && npx migrate reset --force && npx prisma migrate deploy && npx prisma db seed && node ./dist/src/main.js"
        networks:
            - cloud-canvas-network
        restart: unless-stopped
        pull_policy: always
networks:
    cloud-canvas-network:
        driver: bridge
