name: CI/CD
on:
    pull_request:
        branches:
            - development
        types: [closed]

concurrency:
    group: cloud-canvas

jobs:
    CD:
        runs-on: ubuntu-latest

        steps:
            - name: Add SSH known hosts
              run: |
                  mkdir -p ~/.ssh
                  ssh-keyscan -p ${{ secrets.NCP_DEV_INSTANCE_PORT }} ${{ secrets.NCP_DEV_INSTANCE }} >> ~/.ssh/known_hosts
            - name: SSH login and deploy
              run: |
                  printf "%s" "${{ secrets.NCP_DEV_SSH }}" > dev_login.pem
                  chmod 600 dev_login.pem
                  ssh -t -i dev_login.pem ncloud@${{ secrets.NCP_DEV_INSTANCE }} -p ${{ secrets.NCP_DEV_INSTANCE_PORT }} './docker.sh'
