name: PR-BUILD-TEST

on:
    pull_request:
        branches:
            - development
        types: [opened, reopened, synchronize, ready_for_review]

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v3

            - name: Setup Node.js
            - uses: pnpm/action-setup@v2
              with:
                  version: 9.12.3
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'pnpm'
            - run: pnpm install

            - name: Build the project
              run: pnpm build
