name: PR-BUILD-TEST

on:
    pull_request:
        branches:
            - development
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            # Check out repository
            - name: Check out repository
              uses: actions/checkout@v3

            # Setup pnpm and Node.js
            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 9.12.3
                  node-version: 20
                  cache: true

            # Install dependencies using pnpm
            - name: Install dependencies with pnpm
              run: pnpm install

            # Build the project using pnpm
            - name: Build the project
              run: pnpm build
